auth:
- auth_name: default
  auth_type: signed_headers
base_image: oblv_ubuntu_18_04_proxy_python_3_8
meta:
  author: Oblivious Software
  author_email: support@oblivious.ai
  docs: readme.md
  git: https://github.com/oblivious-demo/oblv-smartnoise.git
  version: 0.0.1
paths:
- access: multirole
  path: /upload_data
  short_description: data for training synthetic data generation model
- access: multirole
  path: /confirm_data
  short_description: to confirm status of data upload
- access: multirole
  path: /formats
  short_description: to get available file formats for download
- access: multirole
  path: /samples
  short_description: generate sample data from trained synthetic data model
- access: multirole
  path: /columns
  short_description: get the columns of the data
- access: multirole
  path: /details
  short_description: get the details like model, epsilon, and party names
- access: multirole
  path: /model_status
  short_description: model status [ awaiting data, training, trained ]
roles:
- role_auth: default
  role_cardinality: 2
  role_description: Multirole Users - can access all endpoints
  role_name: multirole
traffic:
  inbound:
  - name: main_io
    port: 80
    type: tcp
  outbound: []
